[package]
name = "nearsay-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.9"
futures = "0.3.31"
mongodb = "3.1.1"
num-cmp = "0.1.0"
serde = "1.0.215"
serde_json = "1.0.133"
socketioxide = "0.15.1"
tokio = {version = "1.41.1", features = ["rt-multi-thread"] }
tower = "0.5.2"
tower-http = { version = "0.5.0", features = ["cors"] }
